import type { Metadata } from "next";
import FavoriteIcon from "@mui/icons-material/Favorite";
import LocationOnIcon from "@mui/icons-material/LocationOn";

import {
  AppBar,
  BottomNavigation,
  BottomNavigationAction,
  Box,
  Container,
  Toolbar,
  Typography,
} from "@mui/material";
import Link from "next/link";
import React from "react";
import RestoreIcon from "@mui/icons-material/Restore";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container>
      <AppBar position="static">
        <Toolbar>
          <Typography variant="h6" component="div">
            <Link href={"/home"}>Song Guessr</Link>
          </Typography>
        </Toolbar>
      </AppBar>

      <Container component="main" sx={{ marginTop: 4, marginBottom: 4 }}>
        {children}
      </Container>

      <Box sx={{ width: "100%" }}>
        <BottomNavigation
          sx={{ backgroundColor: "gray" }}
          showLabels
          value={0}
          // onChange={(event, newValue) => {
          //   setValue(newValue);
          // }}
        >
          <BottomNavigationAction label="Recents" icon={<RestoreIcon />} />
          <BottomNavigationAction label="Favorites" icon={<FavoriteIcon />} />
          <BottomNavigationAction label="Nearby" icon={<LocationOnIcon />} />
        </BottomNavigation>
      </Box>
    </Container>
  );
}
